

platform :ios, '13.0'
inhibit_all_warnings!
use_frameworks! :linkage => :static

post_install do |installer|
  installer.generated_projects.each do |project|
    project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['ONLY_ACTIVE_ARCH'] = 'NO'
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'
#        config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] = "arm64"
      end
    end
  end
end

target 'SJBaseVideoPlayer_Example' do
  pod 'SJBaseVideoPlayer', :path => '../'
end
